MvcDOM/Controllers/ColdController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcDOM.Controllers
{
    public class ColdController : Controller
    {
        private Model1Container db = new Model1Container();

        //
        // GET: /Cold/

        public ActionResult Index(int? id)
        {
           
            var cold_waterнабор = db.Cold_WaterНабор.Include(c => c.Hom);
            //var lst = (from l in db.Cold_WaterНабор
            //           where l.HomID == id
            //           select l).ToList();
            ViewBag.Hom_ID = new SelectList(db.HomItems, "ID", "Apartament_naber");
            return View(cold_waterнабор.ToList());
        }
        //search filter
        public ActionResult ShowFilter(int?id)
        {
            var lst = (from l in db.Cold_WaterНабор
                       where l.HomID == id
                       select l).ToList();
            ViewBag.Hom_ID = new SelectList(db.HomItems, "ID", "Apartament_naber");
            return View(lst);
        }
        //
        // GET: /Cold/Details/5

        public ActionResult Details(int id = 0)
        {
            Cold_Water cold_water = db.Cold_WaterНабор.Find(id);
            if (cold_water == null)
            {
                return HttpNotFound();
            }
            return View(cold_water);
        }

        //
        // GET: /Cold/Create

        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "Apartament_naber");
            
            ViewBag.Nuber = id;

            var water = (from p in db.HomItems
                         where p.ID == id
                         select p.Apartament_naber).FirstOrDefault();
            ViewBag.apartament = water;

            var tarrif = (from t in db.TarrifНабор
                          where t.HomID == id
                          select t.CW).FirstOrDefault();
            ViewBag.tarrif = tarrif;
            var benefit = (from b in db.HomItems
                           where b.ID == id
                           select b.Benefit).FirstOrDefault();
            if (benefit)
            {
                ViewBag.benefit = (tarrif * 25) / 100;

            }
            else { 
             ViewBag.benefit = 0;  
                    }
            var cw = (from p in db.Cold_WaterНабор
                      where p.HomID == id
                      orderby p.ID descending
                      select p.CWT).FirstOrDefault();
            ViewBag.CWT = cw;
            return View();
        }

        //
        // POST: /Cold/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cold_Water cold_water)
        {
            if (ModelState.IsValid)
            {
                db.Cold_WaterНабор.Add(cold_water);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           ViewBag.HomID = new SelectList(db.HomItems, "HomeID", "Apartament_naber", cold_water.HomID);
            return View(cold_water);
        }

        //
        // GET: /Cold/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Cold_Water cold_water = db.Cold_WaterНабор.Find(id);
            if (cold_water == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", cold_water.HomID);
            return View(cold_water);
        }

        //
        // POST: /Cold/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cold_Water cold_water)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cold_water).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", cold_water.HomID);
            return View(cold_water);
        }

        //
        // GET: /Cold/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Cold_Water cold_water = db.Cold_WaterНабор.Find(id);
            if (cold_water == null)
            {
                return HttpNotFound();
            }
            return View(cold_water);
        }

        //
        // POST: /Cold/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cold_Water cold_water = db.Cold_WaterНабор.Find(id);
            db.Cold_WaterНабор.Remove(cold_water);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcDOM/Controllers/ElectricityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcDOM.Controllers
{
    public class ElectricityController : Controller
    {
        private Model1Container db = new Model1Container();

        //
        // GET: /Electricity/

        public ActionResult Index()
        {
            var electricityнабор = db.ElectricityНабор.Include(e => e.Hom);
            return View(electricityнабор.ToList());
        }

        //
        // GET: /Electricity/Details/5

        public ActionResult Details(int id = 0)
        {
            Electricity electricity = db.ElectricityНабор.Find(id);
            if (electricity == null)
            {
                return HttpNotFound();
            }
            return View(electricity);
        }

        //
        // GET: /Electricity/Create

        public ActionResult Create(int?id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            //id homa
            ViewBag.ID = id;
            //namber apartaments
            var nuber = (from n in db.HomItems
                         where n.ID == id
                         select n.Apartament_naber).FirstOrDefault();
            ViewBag.nuber = nuber;
            //tarrif
            var tarrif = (from t in db.TarrifНабор
                          where t.HomID == id
                          select t.E).FirstOrDefault();
            ViewBag.tarrif = tarrif;
            //tarrif up150/250
            var uptarrif = (from u in db.TarrifНабор
                            where u.HomID == id
                            select u.upEL150_250).FirstOrDefault();
            ViewBag.uptarrif = uptarrif;
            //benefit
            var benefit = (from b in db.HomItems
                           where b.ID == id
                           select b.Benefit).FirstOrDefault();
            if (benefit)
            {
                ViewBag.benefit = (tarrif * 25) / 100;

            }
            else
            {
                ViewBag.benefit = 0;
            }
            //gas or not
            var gas = (from g in db.HomItems
                       where g.ID == id
                       select g.Gas).FirstOrDefault();
            if (gas)
            {
                ViewBag.gas = 150;

            }
            else 
            {
                ViewBag.gas = 250;
            }
            //попередні показник
            var e = (from p in db.ElectricityНабор
                      where p.HomID == id
                      orderby p.ID descending
                      select p.EC).FirstOrDefault();
            ViewBag.EP = e;


            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID");
            return View();
        }

        //
        // POST: /Electricity/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Electricity electricity)
        {
            if (ModelState.IsValid)
            {
                db.ElectricityНабор.Add(electricity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", electricity.HomID);
            return View(electricity);
        }

        //
        // GET: /Electricity/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Electricity electricity = db.ElectricityНабор.Find(id);
            if (electricity == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", electricity.HomID);
            return View(electricity);
        }

        //
        // POST: /Electricity/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Electricity electricity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(electricity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", electricity.HomID);
            return View(electricity);
        }

        //
        // GET: /Electricity/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Electricity electricity = db.ElectricityНабор.Find(id);
            if (electricity == null)
            {
                return HttpNotFound();
            }
            return View(electricity);
        }

        //
        // POST: /Electricity/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Electricity electricity = db.ElectricityНабор.Find(id);
            db.ElectricityНабор.Remove(electricity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcDOM/Controllers/HotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcDOM.Controllers
{
    public class HotController : Controller
    {
        private Model1Container db = new Model1Container();

        //
        // GET: /Hot/

        public ActionResult Index()
        {
            var hot_waterнабор = db.Hot_WaterНабор.Include(h => h.Hom);
            return View(hot_waterнабор.ToList());
        }

        //
        // GET: /Hot/Details/5

        public ActionResult Details(int id = 0)
        {
            Hot_Water hot_water = db.Hot_WaterНабор.Find(id);
            if (hot_water == null)
            {
                return HttpNotFound();
            }
            return View(hot_water);
        }

        //
        // GET: /Hot/Create

        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            //id homa
            ViewBag.ID = id;
            //namber apartaments
            var nuber = (from n in db.HomItems
                         where n.ID == id
                         select n.Apartament_naber).FirstOrDefault();
            ViewBag.nuber = nuber;
            //tarrif
            var tarrif = (from t in db.TarrifНабор
                          where t.HomID == id
                          select t.HW).FirstOrDefault();
            ViewBag.tarrif = tarrif;
            //benefit
            var benefit = (from b in db.HomItems
                           where b.ID == id
                           select b.Benefit).FirstOrDefault();
            if (benefit)
            {
                ViewBag.benefit = (tarrif * 25) / 100;

            }
            else
            {
                ViewBag.benefit = 0;
            }
            //попередні показник
            var hw = (from p in db.Hot_WaterНабор
                      where p.HomID == id
                      orderby p.ID descending
                      select p.HWT).FirstOrDefault();
            ViewBag.HWT = hw;
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID");
            return View();
        }

        //
        // POST: /Hot/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hot_Water hot_water)
        {
            if (ModelState.IsValid)
            {
                db.Hot_WaterНабор.Add(hot_water);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", hot_water.HomID);
            return View(hot_water);
        }

        //
        // GET: /Hot/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Hot_Water hot_water = db.Hot_WaterНабор.Find(id);
            if (hot_water == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", hot_water.HomID);
            return View(hot_water);
        }

        //
        // POST: /Hot/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Hot_Water hot_water)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hot_water).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", hot_water.HomID);
            return View(hot_water);
        }

        //
        // GET: /Hot/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Hot_Water hot_water = db.Hot_WaterНабор.Find(id);
            if (hot_water == null)
            {
                return HttpNotFound();
            }
            return View(hot_water);
        }

        //
        // POST: /Hot/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hot_Water hot_water = db.Hot_WaterНабор.Find(id);
            db.Hot_WaterНабор.Remove(hot_water);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcDOM/Controllers/RecordsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcDOM.Controllers
{
    public class RecordsController : Controller
    {
        private Model1Container db = new Model1Container();
        //
        // GET: /Records/

        public ActionResult Index(int? id)
        {

       if (id == null)
    {
        return HttpNotFound();
    }
      // var hom = db.HomItems.Find(id);
    //Hom hom = db.HomItems.Find(id);
   
   // hom.Cold_Water = db.Cold_WaterНабор.Where(m => m.HomID == hom.ID);
     //  var h = db.Cold_WaterНабор.Where(p => p.HomID == id);
      // Cold_Water hom = db.Cold_WaterНабор.Where(p => p.HomID == id).OrderByDescending(x => x.ID).Take(1).Single();    
    // var buts = db.Buts.Include(b=>b.Player).Where(b=>b.Player.TeamId==2) ,2 - здесь id нужной нам команды.

       var cw = (from p in db.Cold_WaterНабор
                 where p.HomID == id 
                 orderby p.ID descending
                 select p).ToList().Take(1);
       var apart = (from p in db.HomItems
                    where p.ID == id
                    select p.Apartament_naber).FirstOrDefault();
       ViewBag.apartament = apart;
            ViewBag.Nuber = id;
    return View(cw);
        }
        public ActionResult Hot(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var hw = (from p in db.Hot_WaterНабор
                      where p.HomID == id
                      orderby p.ID descending
                      select p).ToList().Take(1);
            ViewBag.Nuber = id;
            return View(hw);
        }
        public ActionResult Electro(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var elect = (from p in db.ElectricityНабор
                         where p.HomID == id
                         orderby p.ID descending
                         select p).ToList().Take(1);
            ViewBag.Nuber = id;
            return View(elect);
        
        }
        public ActionResult Sewage(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var sew = (from p in db.SewageНабор
                       where p.HomID == id
                       orderby p.ID descending
                       select p).ToList().Take(1);
            ViewBag.Nuber = id;
            return View(sew);
        }
    }
}

MvcDOM/Views/Records/Electro.cshtml
@model IEnumerable<MvcDOM.Electricity>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<strong>Світло </strong>
<p> 
@Html.ActionLink("+Додати показники по світлу","Create","Electricity",new{id=ViewBag.Nuber},null)
</p>
<div class="row"> 
    <div class="col-md-6"> 
<table class="table table-striped table-bordered">
    <tr>
        <th>
          Поточні
        </th>
        <th>
          Попередні
        </th>
        <th>
          Різниця
        </th>
        <th>
           Спожито
        </th>
        <th>
          Спожито понад норму
        </th>
        <th>
          Сума до сплати
        </th>
        <th>
          Квартира
        </th>
        <th>
          Дата
        </th>
       @* <th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ED)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.L150_250)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.upL150_250)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
       
    </tr>
}

</table>
        </div>
    </div>

MvcDOM/Views/Records/Hot.cshtml
@model IEnumerable<MvcDOM.Hot_Water>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<strong>Гаряча вода</strong>
<p> 
@Html.ActionLink("+Дотаки показники лічильника гарячої води","Create","Hot",new{id=ViewBag.Nuber},null)
</p>
<div class="row"> 
    <div class="col-md-6"> 
<table class="table table-striped table-bordered">
    <tr>
        <th>
           Лічильник1
        </th>
        <th>
           Лічильник2 
        </th>
        <th>
           Разом за лічильником 1 та 2 
        </th>
        <th>
           Попередні показники 
        </th>
        <th>
          Різниця 
        </th>
        <th>
          Сума до сплати 
        </th>
        <th>
          Квартира
        </th>
        <th>
          Дата
        </th>
      @*  <th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HW1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HW0)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HWT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HWP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HWD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
       
    </tr>
}

</table>
</div>
    </div>

MvcDOM/Views/Records/Index.cshtml
@model IEnumerable<MvcDOM.Cold_Water>

@{
    ViewBag.Title = "Index";
    
}
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h2>Останні показники по квартири № @ViewBag.apartament</h2>

<strong>Холодна вода</strong>
<p> 
@Html.ActionLink("+Додати показання лічильника холодної води","Create","Cold",new{id=ViewBag.Nuber},null)
</p>
<div class="row"> 
    <div class="col-md-6"> 
<table class="table table-striped table-bordered">
    <tr>
        <th>
           Лічильник1
        </th>
        <th>
           Лічильник2
        </th>
        <th>
         Разом за лічильником 1 та 2
        </th>
        <th>
           Попередні показники
        </th>
        <th>
          Різниця
        </th>
        <th>
           Сума до сплати
        </th>
        <th>
          Квартира
        </th>
        <th>
          Дата
        </th>
       @* <th></th>*@
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CW1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CW0)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CWT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CWP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CWD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hom.Apartament_naber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        
    </tr>
}
 
</table>
        </div>
    </div>
@Html.Action("Hot","Records")
@Html.Action("Sewage","Records")
@Html.Action("Electro","Records")

MvcDOM/Views/Records/Sewage.cshtml
@model IEnumerable<MvcDOM.Sewage>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<strong>Стоки гарячої води </strong>
<p> 
@Html.ActionLink("+Додати показники по стокам гарячої води","Create","Sewage",new{id=ViewBag.Nuber},null)
</p>
<div class="row"> 
    <div class="col-md-6"> 
<table class="table table-striped table-bordered">
    <tr>
        <th>
           Лічильник1 
        </th>
        <th>
          Лічильник2  
        </th>
        <th>
           Разом за лічильником 1 та 2 
        </th>
        <th>
          Попередні показники 
        </th>
        <th>
           Різниця 
        </th>
        <th>
         Сума до сплати 
        </th>
        <th>
         Дата   
        </th>
        <th>
         Квартира 
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.S1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.S0)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ST)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HomID)
        </td>
       
    </tr>
}

</table>
        </div>
    </div>