MvcHOME/Controllers/GazController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcHOME.Controllers
{
    public class GazController : Controller
    {
        private Model1Container db = new Model1Container();

        //
        // GET: /Gaz/

        public ActionResult Index()
        {
            var gasнабор = db.GasНабор.Include(g => g.Hom);
            return View(gasнабор.ToList());
        }

        //
        // GET: /Gaz/Details/5

        public ActionResult Details(int id = 0)
        {
            Gas gas = db.GasНабор.Find(id);
            if (gas == null)
            {
                return HttpNotFound();
            }
            return View(gas);
        }

        //
        // GET: /Gaz/Create

        public ActionResult Create()
        {
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "Apartament_naber");
            return View();
        }

        //
        // POST: /Gaz/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Gas gas)
        {
            if (ModelState.IsValid)
            {
                db.GasНабор.Add(gas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", gas.HomID);
            return View(gas);
        }

        //
        // GET: /Gaz/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Gas gas = db.GasНабор.Find(id);
            if (gas == null)
            {
                return HttpNotFound();
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", gas.HomID);
            return View(gas);
        }

        //
        // POST: /Gaz/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Gas gas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HomID = new SelectList(db.HomItems, "ID", "ID", gas.HomID);
            return View(gas);
        }

        //
        // GET: /Gaz/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Gas gas = db.GasНабор.Find(id);
            if (gas == null)
            {
                return HttpNotFound();
            }
            return View(gas);
        }

        //
        // POST: /Gaz/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gas gas = db.GasНабор.Find(id);
            db.GasНабор.Remove(gas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcHOME/Views/Gaz/Create.cshtml
@model MvcHOME.Gas

@{
    ViewBag.Title = "Create";
}

<h2>Створити</h2>

@using (Html.BeginForm("Create", "Gaz", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Газ</legend>

        <div class="form-group">
            @Html.LabelFor(model => model.GC,"Поточні", new { @class = "col-md-2 control-label" })
        
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.GC, new  { @class="form-control",  @placeholder="Поточні" })
            @Html.ValidationMessageFor(model => model.GC)
        </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.GP,"Попередні", new { @class = "col-md-2 control-label" })
        
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.GP, new  { @class="form-control",  @placeholder="Попередні" })
            @Html.ValidationMessageFor(model => model.GP)
        </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.GD,"Спожито", new { @class = "col-md-2 control-label" })
        
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.GD, new  { @class="form-control",  @placeholder="Спожито" })
            @Html.ValidationMessageFor(model => model.GD)
        </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.Privelege,"Пільга", new { @class = "col-md-2 control-label" })
        
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.Privelege, new  { @class="form-control",  @placeholder="Пільга" })
            @Html.ValidationMessageFor(model => model.Privelege)
        </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.Sum,"До сплати", new { @class = "col-md-2 control-label" })
        
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.Sum, new  { @class="form-control",  @placeholder="До сплати" })
            @Html.ValidationMessageFor(model => model.Sum)
        </div>
</div>
        <div class="form-group">
            @Html.LabelFor(model => model.Data,"Дата", new { @class = "col-md-2 control-label" })
       
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.Data, new  { @class="form-control",  @placeholder="Дата" })
            @Html.ValidationMessageFor(model => model.Data)
        </div>
 </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HomID, "Hom", new { @class = "col-md-2 control-label" })
       
        <div class="col-md-2">
            @Html.DropDownList("HomID", String.Empty)
            @Html.ValidationMessageFor(model => model.HomID)
        </div>
 </div>
        
             <div class="form-group">
           <div class="col-md-1">
            <input type="submit" value="Create" class="btn btn-default" />
               </div>
         </div>
        
    </fieldset>
}

<div>
    <ul class="pagination">
        <li>
  @Html.ActionLink("Back to List", "Index")
        </li>
    </ul>
  
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
  $(function() {
      $("#Data").datepicker({
          dateFormat: "yy-mm-dd"
      });
  });
  </script>
      <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

MvcHOME/Views/Gaz/Delete.cshtml
@model MvcHOME.Gas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Gas</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GC)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GP)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GP)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GD)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GD)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Privelege)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Privelege)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sum)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sum)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Data)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Data)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hom.ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hom.ID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcHOME/Views/Gaz/Details.cshtml
@model MvcHOME.Gas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Gas</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GC)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GP)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GP)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GD)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GD)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Privelege)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Privelege)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sum)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sum)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Data)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Data)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hom.ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hom.ID)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcHOME/Views/Gaz/Edit.cshtml
@model MvcHOME.Gas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Gas</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.GC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GC)
            @Html.ValidationMessageFor(model => model.GC)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GP)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GP)
            @Html.ValidationMessageFor(model => model.GP)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GD)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GD)
            @Html.ValidationMessageFor(model => model.GD)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Privelege)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Privelege)
            @Html.ValidationMessageFor(model => model.Privelege)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sum)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sum)
            @Html.ValidationMessageFor(model => model.Sum)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Data)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Data)
            @Html.ValidationMessageFor(model => model.Data)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HomID, "Hom")
        </div>
        <div class="editor-field">
            @Html.DropDownList("HomID", String.Empty)
            @Html.ValidationMessageFor(model => model.HomID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcHOME/Views/Gaz/Index.cshtml
@model IEnumerable<MvcHOME.Gas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayName("Поточні")
        </th>
        <th>
            @Html.DisplayName("Попередні")
        </th>
        <th>
            @Html.DisplayName("Спожито")
        </th>
        <th>
            @Html.DisplayName("Пільга")
        </th>
        <th>
            @Html.DisplayName("До сплати")
        </th>
        <th>
            @Html.DisplayName("Дата")
        </th>
        <th>
            @Html.DisplayName("Квартира")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Privelege)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hom.Apartament_naber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>